- README.md
Reverts H4K3R13/The-Hello-World-Project#5 @H4K3R13 @SIBI-MS @
> Revert "upadating"

- HelloWorld.rb
- README.md
> Added HelloWorld in Ruby

- HelloWorld.r
- README.md
This PR is adding the R version of a `Hello World` program and the badge in the README.md .
> Hello World in R

- HelloWorld.dart
I hope its acceptable its my first time contributing!!
> HelloWorld.Dart

- HelloWorld.i
> Hello World in Yarick

- HelloWorld.coffee
> Added HelloWorld in CoffeeScript

- HelloWorld.carbon
Successfully wrote hello world in carbon and tested it 
closes #77 
Compiled Result
> Added HelloWorld in carbon

- HelloWorld.mojo
Fixes: #72 
Added Hello World in **MOJO**
> Added HelloWorld in Mojo

- HelloWorld.groovy
This PR adds hello world program in Groovy. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Groovy

- HelloWorld.pl
This PR adds hello world program in Prolog. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Prolog

- HelloWorld.d
This PR adds hello world program in D. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in D

- HelloWorld.nim
This PR adds hello world program in Nim. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Nim

- HelloWorld.ml
This PR adds hello world program in OCaml. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in OCaml

- HelloWorld.jl
This PR adds hello world program in Julia. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Julia

- HelloWorld.vb
This PR adds hello world program in Visual Basic. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Visual Basic

- HelloWorld.m
This PR adds hello world program in Mercury. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Mercury

- HelloWorld.lean
This PR adds hello world program in Lean. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Lean

- HelloWorld.red
This PR adds hello world program in Red. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Red

- HelloWorld.purs
This PR adds hello world program in PureScript. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in PureScript

- HelloWorld.bsq
This PR adds hello world program in Bosque. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Bosque

- HelloWorld.re
This PR adds hello world program in Reason. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Reason

- HelloWorld.ring
This PR adds hello world program in Ring. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Ring

- HelloWorld.cuneiform
This PR adds hello world program in Cuneiform. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Cuneiform

- HelloWorld.opa
This PR adds hello world program in Opa. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Opa

- HelloWorld.bal
This PR adds hello world program in Ballerina. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Ballerina

- HelloWorld.p
This PR adds hello world program in P. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in P

- HelloWorld.elm
This PR adds hello world program in Elm. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Elm

- HelloWorld.ceylon
This PR adds hello world program in Ceylon. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Ceylon

- HelloWorld.jai
This PR adds hello world program in Jai. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Jai

- HelloWorld.raku
This PR adds hello world program in Raku. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Raku

- HelloWorld.hack
This PR adds hello world program in Hack. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Hack

- HelloWorld.p4
This PR adds hello world program in P4. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in P4

- HelloWorld.qs
This PR adds hello world program in Q#. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Q#

- HelloWorld.aj
This PR adds hello world program in AspectJ. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in AspectJ

- HelloWorld.hx
This PR adds hello world program in Haxe. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Haxe

- HelloWorld.gsp
This PR adds hello world program in Gosu. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Gosu

- HelloWorld.whiley
This PR adds hello world program in Whiley. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Whiley

- HelloWorld.agda
This PR adds hello world program in Agda. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Agda

- HelloWorld.n
This PR adds hello world program in Nemerle. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Nemerle

- HelloWorld.pde
This PR adds hello world program in Processing. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Processing

- HelloWorld.dfy
This PR adds hello world program in Dafny. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Dafny

- HelloWorld.idr
This PR adds hello world program in Idris. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Idris

- HelloWorld.io
This PR adds hello world program in Io. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Io

- HelloWorld.boo
This PR adds hello world program in Boo. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Boo

- HelloWorld.gs
This PR adds hello world program in Genie. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Genie

- HelloWorld.fan
This PR adds hello world program in Fantom. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Fantom

- HelloWorld.sd7
This PR adds hello world program in Seed7. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Seed7

- HelloWorld.vala
This PR adds hello world program in Vala. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Vala

- HelloWorld.chpl
This PR adds hello world program in Chapel. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Chapel

- HelloWorld.oxygene
This PR adds hello world program in Oxygene. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Oxygene

- HelloWorld.ft
This PR adds hello world program in Fortress. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Fortress

- HelloWorld.cobra
This PR adds hello world program in Cobra. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Cobra

- HelloWorld.clj
This PR adds hello world program in Clojure. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Clojure

- HelloWorld.nut
This PR adds hello world program in Squirrel. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Squirrel

- HelloWorld.ps1
This PR adds hello world program in Windows PowerShell. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Windows PowerShell

- HelloWorld.Mod
This PR adds hello world program in Oberon-07. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Oberon-07

- HelloWorld.factor
This PR adds hello world program in Factor. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Factor

- HelloWorld.s
Issue no: #159 
I added the hello world program in arm architecture assembly instructions.
> Feat: Hello world arm assembly instructions

- HelloWorld.dpl
I have added Hello WOrld Program in Delphi Language .
> Added Hello World Program in Delphi Language

- HelloWorld.image
This PR adds hello world program in Squeak. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Squeak

- HelloWorld.e
This PR adds hello world program in E. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in E

- HelloWorld.pb
This PR adds hello world program in PureBasic. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in PureBasic

- HelloWorld.zpl
This PR adds hello world program in ZPL. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in ZPL

- HelloWorld.fscript
This PR adds hello world program in F-Script. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in F-Script

- HelloWorld.euphoria
This PR adds hello world program in Euphoria. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Euphoria

- HelloWorld.sl
This PR adds hello world program in S-Lang. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in S-Lang

- HelloWorld.dat
This PR adds hello world program in AMPL. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in AMPL

- HelloWorld.applescript
This PR adds hello world program in AppleScript. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in AppleScript

- HelloWorld.zsh
This PR adds hello world program in zsh. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in zsh

- HelloWorld.fth
This PR adds hello world program in Forth. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Forth

- HelloWorld.pike
This PR adds hello world program in Pike. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Pike

- HelloWorld.k
This PR adds hello world program in K. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in K

- HelloWorld.lgt
This PR adds hello world program in Logtalk. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Logtalk

- HelloWorld.ns
This PR adds hello world program in NewtonScript. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in NewtonScript

- HelloWorld.hb
This PR adds hello world program in Harbour. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Harbour

- HelloWorld.lc
This PR adds hello world program in LiveCode-Transcript. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in LiveCode-Transcript

- HelloWorld.dylan
This PR adds hello world program in Dylan. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Dylan

- HelloWorld.pdl
This PR adds hello world program in Perl-Data-Language-(PDL). I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Perl-Data-Language-(PDL)

- HelloWorld.ijs
This PR adds hello world program in J. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in J

- HelloWorld.amos
This PR adds hello world program in AMOS-BASIC. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in AMOS-BASIC

- HelloWorld.pico
This PR adds hello world program in Pico. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Pico

- HelloWorld.module
This PR adds hello world program in Gambas. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Gambas

- HelloWorld.rkt
This PR adds hello world program in Racket. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Racket

- HelloWorld.lasso
This PR adds hello world program in Lasso. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Lasso

- HelloWorld.self
This PR adds hello world program in Self. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Self

- HelloWorld.oz
This PR adds hello world program in Oz. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Oz

- HelloWorld.es
This PR adds hello world program in ECMAScript. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in ECMAScript

- HelloWorld.q
This PR adds hello world program in Q. I kindly request the repository maintainers to review and merge the PR.
> Add hello world in Q

- helloworld.BS
This PR  is solving #186  @H4K3R13
> Added HelloWorld in QBASIC

- HelloWorld.Makefile
- HelloWorld.sv
- HelloWorld.v.v
Hi ,
I have added an hello world program based on GNU make 
a popular tool of GNU project for generation of executables.
Also added for systemverilog and verilog.
Please make it as a part of Hacktoberfest.
> Added HelloWorld in GNU Make

- CONTRIBUTING.md
I have made my contribution to the project and ready to do so more.
> Add Gideon Kipkorir Yegon to Contributors list

- Helloworld.xojo
Hello @H4K3R13  I have added helloworld in xojo language. Please review this PR.
> Added Helloworld in Xojo

- HelloWorld.bpcl
> Add hello world in BPCL

- HelloWorld.alg
> Add hello world in ALGOL
